// Default workspace/user settings (mirrors Clockify's WorkspaceSettingsDto / UserSettingsDto)
export const DEFAULT_WORKSPACE_SETTINGS = {
  timeRoundingInReports: false,
  onlyAdminsSeeBillableRates: true,
  onlyAdminsCreateProject: true,
  onlyAdminsSeeDashboard: false,
  defaultBillableProjects: true,
  lockTimeEntries: null,
  lockTimeZone: null,
  round: { round: 'Round to nearest', minutes: '15' },
  projectFavorites: true,
  canSeeTimeSheet: true,
  canSeeTracker: true,
  projectPickerSpecialFilter: false,
  forceProjects: false,
  forceTasks: false,
  forceTags: false,
  forceDescription: false,
  onlyAdminsSeeAllTimeEntries: false,
  onlyAdminsSeePublicProjectsEntries: false,
  trackTimeDownToSecond: true,
  projectGroupingLabel: 'client',
  projectLabel: 'project',
  taskLabel: 'task',
  adminOnlyPages: [],
  automaticLock: null,
  onlyAdminsCreateTag: false,
  onlyAdminsCreateTask: true,
  onlyAdminsCanChangeBillableStatus: false,
  timeTrackingMode: 'DEFAULT',
  isProjectPublicByDefault: true,
  multiFactorEnabled: false,
  numberFormat: 'COMMA_PERIOD',
  currencyFormat: 'CURRENCY_SPACE_VALUE',
  durationFormat: 'FULL',
  activeBillableHours: false,
  workingDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
  workCapacity: 'PT8H',
  entityCreationPermissions: {
    whoCanCreateProjectsAndClients: 'ADMINS',
    whoCanCreateTags: 'EVERYONE',
    whoCanCreateTasks: 'ADMINS',
  },
  approvalPeriod: 'WEEKLY',
  kioskPinRequired: true,
  breaks: true,
  favoriteEntries: true,
  timeOffEnabled: true,
  schedulingEnabled: true,
  expensesEnabled: true,
  invoicingEnabled: true,
  approvalsEnabled: true,
  features: [],
};

export const DEFAULT_USER_SETTINGS = {
  weekStart: 'MONDAY',
  timeZone: 'UTC',
  timeFormat: 'HOUR24',
  dateFormat: 'DD/MM/YYYY',
  sendNewsletter: false,
  weeklyUpdates: false,
  longRunning: false,
  scheduledReports: true,
  approval: true,
  pto: true,
  alerts: true,
  reminders: true,
  invoiceReminders: true,
  timeTrackingManual: false,
  summaryReportSettings: { group: 'Project', subgroup: 'Time Entry' },
  isCompactViewOn: false,
  dashboardSelection: 'ME',
  dashboardViewType: 'PROJECT',
  dashboardPinToTop: false,
  projectListCollapse: 50,
  collapseAllProjectLists: false,
  groupSimilarEntriesDisabled: false,
  myStartOfDay: '09:00',
  projectPickerTaskFilter: false,
  lang: 'PT_BR',
  multiFactorEnabled: false,
  theme: 'DEFAULT',
  scheduling: true,
  onboarding: false,
  showOnlyWorkingDays: false,
};

export function mergeSettings(defaults, stored) {
  return { ...defaults, ...(stored || {}) };
}
